### ISSUE TITLE
You are so smart for doing this

### ISSUE THREAD

**Issue by MartinLunn** [Chris1221/dotfiles#1]
btw, always make sure that the makefile itself is a dependency in a makefile.

Words from the experienced....and the ones who've spent years trying to figure out what the bug is.

**Comment by Chris1221** [comment]
LOL. Which `makefile`? :) I tried to use `stow` within a `makefile` but I think something went wonky with `make` spawning a subshell with every line so I just gave up and now I can do `stow *` instead. :) How do you manage yours?

**Comment by Chris1221** [comment]
with `alias stow=stow -t ~/` cause if not then it stows to the grandfather directory (`../../`) and I put this in `~/repos/dotfiles` so it was going to the wrong spot*
